
name: AutoCheck
on:
  schedule:
  - cron: 0 16 * * *  #  分钟（0） 小时（0） 日（*） 月（*） 星期几（*）
  workflow_dispatch:

jobs:
  build:
    name: TVSpider
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
    steps:
      - name: Clone TVSpider Repository
        uses: actions/checkout@v3
        with:
          repository: jadehh/AutoCheckin

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip
      - name: Install requirements
        run: |
          pip install -r ./requirements.txt
      - name: Auto Check
        run: |
          python ./main.py --aliToken  "${{ secrets.ALI_TOKEN }}" --quarkCookie  "${{ secrets.QUARK_COOKIE}}" --telChatId "${{ secrets.TEL_CHATID}}" --telToken "${{ secrets.TEL_TOKEN}}"
  